#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &



#bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII IX X
bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
#bspc config window_gap         5 
bspc config window_gap         1 

bspc config normal_border_color \#5d1229
bspc config focused_border_color \#B9CDAA

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a feh state=floating
bspc rule -a "VirtualBox Machine" state=floating
bspc rule -a wpp state=floating
bspc rule -a gpick state=floating
bspc rule -a Gpick state=floating
bspc rule -a Think-it-Through state=floating
bspc rule -a leap-linux state=floating

bspc rule -a voice-commander desktop=^9
bspc rule -a protonmail-bridge desktop=^9
bspc rule -a Thunderbird desktop=^9

bspc rule -a Zathura state=tiled

copyq &
pnmixer&
feh --randomize --bg-scale ~/Pictures/wp/*
#xrandr --output DisplayPort-1 --mode 2560x1440 --rate 144 --right-of DisplayPort-0
#xrandr --output DisplayPort-0 --primary
xrandr --output DP-1 --mode 2560x1440 --rate 144 --right-of DP-0
xrandr --output DP-0 --primary
protonmail-bridge  --no-window &
thunderbird &
#voice-commander &
xrandr --output DP-2 --mode 2560x1440 --rate 144
steam -silent&
#compton &
#/home/inathero/Scripts/linuxsampler-piano &
/home/inathero/Gits/leap-linux/build/leap-linux &
wmctrl -r Thunderbird -t 9 &
$HOME/.config/polybar/launch.sh &
